aspnetCoreVersion: "3.1"
useSwashbuckle: "false"
classModifier: "abstract"
generateBody: "false"
operationIsAsync: "false"
operationResultTask: "true"
returnICollection: "true"
useCollection: "false"
packageCopyright: "Banco BPI Copyright"
modelClassModifier: "partial"